name: Dispatch Cogfy Sync

on:
  workflow_dispatch:

jobs:
  run-scheduled-scraper:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nitaibezerra/govbrnews-scraper:latest
      options: --workdir /app

    steps:
      - name: Set ONE_WEEK_AGO environment variable
        run: |
          echo "ONE_WEEK_AGO=$(date -d '7 days ago' +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Print date information
        run: |
          echo "Scheduled run. Using min-date=$ONE_WEEK_AGO"

      - name: Upload to Cogfy
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          COGFY_API_KEY: ${{ secrets.COGFY_API_KEY }}
        run: |
          cd /app
          python src/upload_to_cogfy_manager.py \
            --start-date $ONE_WEEK_AGO