name: Scheduled Scraper

on:
  schedule:
    # Runs every day at 4AM UTC (midnight Brasília)
    - cron: '0 4 * * *'

jobs:
  run-scheduled-scraper:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/nitaibezerra/govbrnews-scraper:latest
      options: --workdir /app

    steps:
      - name: Set date environment variables
        run: |
          echo "YESTERDAY=$(date -d '1 day ago' +'%Y-%m-%d')" >> $GITHUB_ENV
          echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Print date information
        run: |
          echo "Scheduled run. Processing from $YESTERDAY to $TODAY"

      - name: Run scraper
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          cd /app
          python src/main.py scrape \
            --start-date $YESTERDAY \
            --end-date $TODAY

      - name: Upload to Cogfy
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
          COGFY_API_KEY: ${{ secrets.COGFY_API_KEY }}
        run: |
          cd /app
          python src/upload_to_cogfy_manager.py \
            --start-date $YESTERDAY \
            --end-date $TODAY

      - name: Wait before grouping
        run: |
          echo "Waiting 30 minutes before running news grouper..."
          sleep 1800

      - name: Group news by theme
        env:
          COGFY_API_KEY: ${{ secrets.COGFY_API_KEY }}
        run: |
          cd /app
          python src/news_grouper.py \
            --start-date $YESTERDAY \
            --end-date $TODAY